In [55]:
import pandas as pd

# Read a .csv from a URL with pandas

### Target website:https://www.football-data.co.uk/data.php

In [56]:
#Reading 1 csv file from the website
df_premier21 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/E0.csv")

In [57]:
# showing dataframe
df_premier21

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,13/08/2021,20:00,Brentford,Arsenal,2,0,H,1,0,...,1.62,0.50,1.75,2.05,1.81,2.13,2.05,2.17,1.80,2.09
1,E0,14/08/2021,12:30,Man United,Leeds,5,1,H,1,0,...,2.25,-1.00,2.05,1.75,2.17,1.77,2.19,1.93,2.10,1.79
2,E0,14/08/2021,15:00,Burnley,Brighton,1,2,A,1,0,...,1.62,0.25,1.79,2.15,1.81,2.14,1.82,2.19,1.79,2.12
3,E0,14/08/2021,15:00,Chelsea,Crystal Palace,3,0,H,2,0,...,1.94,-1.50,2.05,1.75,2.12,1.81,2.16,1.93,2.06,1.82
4,E0,14/08/2021,15:00,Everton,Southampton,3,1,H,0,1,...,1.67,-0.50,2.05,1.88,2.05,1.88,2.08,1.90,2.03,1.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,22/05/2022,16:00,Crystal Palace,Man United,1,0,H,1,0,...,2.04,0.25,1.68,2.15,1.74,2.23,1.88,2.25,1.74,2.16
376,E0,22/05/2022,16:00,Leicester,Southampton,4,1,H,0,0,...,2.63,-0.75,1.83,2.07,1.88,2.03,1.94,2.26,1.87,2.01
377,E0,22/05/2022,16:00,Liverpool,Wolves,3,1,H,1,1,...,3.28,-2.50,2.02,1.77,2.06,1.83,2.19,1.99,2.07,1.80
378,E0,22/05/2022,16:00,Man City,Aston Villa,3,2,H,0,1,...,3.36,-2.25,2.06,1.84,2.05,1.86,2.09,2.03,2.01,1.87
379,E0,22/05/2022,16:00,Norwich,Tottenham,0,5,A,0,2,...,2.40,1.50,1.95,1.95,1.96,1.94,2.16,1.98,1.99,1.89

In [58]:
# rename columns
df_premier21.rename(columns = {"FTHG":"home_goals","FTAG":"away_goals"},inplace = True)

In [59]:
# show new dataframe
df_premier21

,Div,Date,Time,HomeTeam,AwayTeam,home_goals,away_goals,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,13/08/2021,20:00,Brentford,Arsenal,2,0,H,1,0,...,1.62,0.50,1.75,2.05,1.81,2.13,2.05,2.17,1.80,2.09
1,E0,14/08/2021,12:30,Man United,Leeds,5,1,H,1,0,...,2.25,-1.00,2.05,1.75,2.17,1.77,2.19,1.93,2.10,1.79
2,E0,14/08/2021,15:00,Burnley,Brighton,1,2,A,1,0,...,1.62,0.25,1.79,2.15,1.81,2.14,1.82,2.19,1.79,2.12
3,E0,14/08/2021,15:00,Chelsea,Crystal Palace,3,0,H,2,0,...,1.94,-1.50,2.05,1.75,2.12,1.81,2.16,1.93,2.06,1.82
4,E0,14/08/2021,15:00,Everton,Southampton,3,1,H,0,1,...,1.67,-0.50,2.05,1.88,2.05,1.88,2.08,1.90,2.03,1.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,22/05/2022,16:00,Crystal Palace,Man United,1,0,H,1,0,...,2.04,0.25,1.68,2.15,1.74,2.23,1.88,2.25,1.74,2.16
376,E0,22/05/2022,16:00,Leicester,Southampton,4,1,H,0,0,...,2.63,-0.75,1.83,2.07,1.88,2.03,1.94,2.26,1.87,2.01
377,E0,22/05/2022,16:00,Liverpool,Wolves,3,1,H,1,1,...,3.28,-2.50,2.02,1.77,2.06,1.83,2.19,1.99,2.07,1.80
378,E0,22/05/2022,16:00,Man City,Aston Villa,3,2,H,0,1,...,3.36,-2.25,2.06,1.84,2.05,1.86,2.09,2.03,2.01,1.87
379,E0,22/05/2022,16:00,Norwich,Tottenham,0,5,A,0,2,...,2.40,1.50,1.95,1.95,1.96,1.94,2.16,1.98,1.99,1.89

# Read .csv from Multiple URLs with pandas

In [81]:
#--https://www.football-data.co.uk/mmz4281/2122/E0.csv
#--https://www.football-data.co.uk/mmz4281/2122/E1.csv

### Link: Root + season + league

In [61]:
# Link stracture
"https://www.football-data.co.uk/mmz4281/" + "2122" + "/" + "E0" + ".csv"

'https://www.football-data.co.uk/mmz4281/2122/E0.csv'

In [62]:
# create a root variable
root = "https://www.football-data.co.uk/mmz4281/"

# 2.1 Multiple Leagues

https://www.football-data.co.uk/mmz4281/2122/E0.csv
https://www.football-data.co.uk/mmz4281/2122/E1.csv
https://www.football-data.co.uk/mmz4281/2122/E2.csv
https://www.football-data.co.uk/mmz4281/2122/E3.csv
https://www.football-data.co.uk/mmz4281/2122/EC.csv

In [63]:
# creating list of leagues
leagues = ['E0', 'E1', 'E2', 'E3', 'EC']
frames = []
# looping througn leagues,read multiple csv and append it into a list
for league in leagues:
    df = pd.read_csv(root + '2122' + '/' + league +'.csv', encoding='unicode_escape')
    frames.append(df)

In [64]:
# length of dataframes
len(frames)

5

In [65]:
# show 1st , 2nd and 3rd elementes
frames[1]

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E1,06/08/2021,19:45,Bournemouth,West Brom,2,2,D,1,1,...,1.84,-0.25,2.13,1.78,2.13,1.80,2.16,1.83,2.09,1.77
1,E1,07/08/2021,15:00,Blackburn,Swansea,2,1,H,1,0,...,1.70,-0.25,1.77,2.14,1.83,2.09,1.87,2.17,1.81,2.04
2,E1,07/08/2021,15:00,Bristol City,Blackpool,1,1,D,1,0,...,1.66,-0.25,1.90,2.00,1.92,1.99,1.92,2.01,1.89,1.95
3,E1,07/08/2021,15:00,Cardiff,Barnsley,1,1,D,0,0,...,1.62,-0.25,2.05,1.75,2.14,1.80,2.19,1.80,2.11,1.75
4,E1,07/08/2021,15:00,Derby,Huddersfield,1,1,D,1,1,...,1.60,-0.25,1.88,2.02,1.88,2.01,1.90,2.07,1.87,1.98
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,E1,07/05/2022,12:30,Preston,Middlesbrough,4,1,H,2,0,...,2.15,0.75,1.84,2.06,1.88,2.03,2.00,2.09,1.89,1.96
548,E1,07/05/2022,12:30,Sheffield United,Fulham,4,0,H,3,0,...,2.09,-0.25,1.75,2.05,1.79,2.12,1.85,2.13,1.81,2.03
549,E1,07/05/2022,12:30,Stoke,Coventry,1,1,D,1,1,...,2.15,-0.25,1.91,1.99,1.95,1.95,1.95,2.01,1.90,1.95
550,E1,07/05/2022,12:30,Swansea,QPR,0,1,A,0,0,...,2.71,-0.50,1.92,1.98,1.94,1.96,2.00,1.99,1.95,1.90
551,E1,07/05/2022,12:30,West Brom,Barnsley,4,0,H,2,0,...,2.67,-1.75,1.88,2.02,1.91,1.98,1.99,2.06,1.90,1.95

#          2.2 Multiple seasons

In [66]:
 for season in range(15, 21):
     print(str(season) + str(season+1))

1516
1617
1718
1819
1920
2021

In [69]:
# creating list of leagues
leagues = ['E0', 'E2', 'E3',]
frames = []
# looping througn leagues,read multiple csv and append it into a list
for league in leagues:
    for season in range(15, 21):
        df = pd.read_csv(root + str(season) + str(season+1) + '/' + league +'.csv')
        df.insert(1, 'season', season)
        frames.append(df)

In [70]:
#total frames (6 seasons * 3 leagues)
len(frames)

18

In [71]:
# show 1st and last elements( new season columns was created)
frames[0]

,Div,season,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,BbAv<2.5,BbAH,BbAHh,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA,PSCH,PSCD,PSCA
0,E0,15,08/08/2015,Bournemouth,Aston Villa,0,1,A,0,0,...,1.79,26,-0.50,1.98,1.93,1.99,1.92,1.82,3.88,4.70
1,E0,15,08/08/2015,Chelsea,Swansea,2,2,D,2,1,...,1.99,27,-1.50,2.24,2.16,1.80,1.73,1.37,5.04,10.88
2,E0,15,08/08/2015,Everton,Watford,2,2,D,0,1,...,1.96,26,-1.00,2.28,2.18,1.76,1.71,1.75,3.76,5.44
3,E0,15,08/08/2015,Leicester,Sunderland,4,2,H,3,0,...,1.67,26,-0.50,2.00,1.95,1.96,1.90,1.79,3.74,5.10
4,E0,15,08/08/2015,Man United,Tottenham,1,0,H,1,0,...,2.01,26,-1.00,2.20,2.09,1.82,1.78,1.64,4.07,6.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,15,15/05/2016,Stoke,West Ham,2,1,H,0,1,...,2.27,30,0.25,2.11,2.03,1.87,1.83,3.05,4.00,2.26
376,E0,15,15/05/2016,Swansea,Man City,1,1,D,1,1,...,2.45,31,1.00,2.14,2.05,1.85,1.81,7.05,5.00,1.47
377,E0,15,15/05/2016,Watford,Sunderland,2,2,D,0,1,...,2.10,29,-0.50,2.06,2.01,1.91,1.85,1.64,4.52,5.27
378,E0,15,15/05/2016,West Brom,Liverpool,1,1,D,1,1,...,2.09,30,-0.25,2.10,2.05,1.86,1.81,2.61,3.75,2.70
379,E0,15,17/05/2016,Man United,Bournemouth,3,1,H,1,0,...,2.20,29,-0.75,1.88,1.84,2.08,2.02,1.50,4.60,7.03

In [72]:
# show 1st and last elements( new season columns was created)
frames[17]

,Div,season,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E3,20,12/09/2020,15:00,Barrow,Stevenage,1,1,D,1,...,1.76,-0.25,1.95,1.90,1.93,1.98,1.98,1.99,1.91,1.92
1,E3,20,12/09/2020,15:00,Bolton,Forest Green,0,1,A,0,...,1.79,-0.25,2.02,1.83,2.04,1.87,2.09,1.90,2.00,1.83
2,E3,20,12/09/2020,15:00,Bradford,Colchester,0,0,D,0,...,1.65,-0.25,2.07,1.72,2.11,1.82,2.20,1.82,2.09,1.76
3,E3,20,12/09/2020,15:00,Cambridge,Carlisle,3,0,H,2,...,1.70,-0.25,1.98,1.88,2.02,1.88,2.04,1.90,1.99,1.84
4,E3,20,12/09/2020,15:00,Cheltenham,Morecambe,1,2,A,1,...,1.75,-0.50,1.83,2.02,1.87,2.04,1.88,2.09,1.83,2.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,E3,20,08/05/2021,15:00,Port Vale,Mansfield,0,3,A,0,...,1.84,0.25,1.90,1.95,1.89,2.00,1.95,2.07,1.85,1.97
548,E3,20,08/05/2021,15:00,Scunthorpe,Stevenage,0,1,A,0,...,1.73,0.50,1.80,2.05,1.84,2.06,1.87,2.14,1.77,2.07
549,E3,20,08/05/2021,15:00,Southend,Newport County,1,1,D,1,...,1.44,0.50,1.93,1.93,1.94,1.94,1.97,1.97,1.91,1.91
550,E3,20,08/05/2021,15:00,Tranmere,Colchester,0,0,D,0,...,1.59,-0.75,2.05,1.80,2.05,1.85,2.08,1.89,2.01,1.82
551,E3,20,08/05/2021,16:00,Salford,Leyton Orient,3,0,H,1,...,1.87,-1.00,1.98,1.88,1.99,1.90,2.01,1.96,1.96,1.86

# Organize All Data in The Dictionary

In [73]:
# Create a dictionary with original name of league as a key
dict_countries = {'Spanish La Liga':'SP1',
                  'Spanish Segunda Division':'SP2',
                  'German Bundesliga':'D1',
                  'English Premier League':'E0',
                 'English League 1':'E1',
                 'English League 2':'E2'}

In [74]:
# get dictionary datas
dict_countries['English League 2']

'E2'

In [75]:
for league in dict_countries:
    print(dict_countries[league])

SP1
SP2
D1
E0
E1
E2

In [76]:
dict_historical_data = {}

# looping through key elements

# creating list of leagues
# leagues = ['E0', 'E2', 'E3',]
frames = []
# looping through key elements
for league in dict_countries:
    for season in range(15, 21):
        df = pd.read_csv(root + str(season) + str(season+1) + '/' + dict_countries[league] +'.csv')
        df.insert(1, 'season', season)
        frames.append(df)
    df_concat = pd.concat(frames)
    dict_historical_data[league] = df_concat

In [80]:
# show dataframe inside dict_historical_data
dict_historical_data['English Premier League']

,Div,season,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,Referee
0,SP1,15,21/08/15,Malaga,Sevilla,0,0,D,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,SP1,15,22/08/15,Ath Madrid,Las Palmas,1,0,H,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,SP1,15,22/08/15,Espanol,Getafe,1,0,H,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SP1,15,22/08/15,La Coruna,Sociedad,0,0,D,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,SP1,15,22/08/15,Vallecano,Valencia,0,0,D,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,20,23/05/2021,Liverpool,Crystal Palace,2,0,H,1.0,0.0,...,-2.25,1.86,2.04,1.88,2.03,1.98,2.14,1.88,2.00,C Pawson
376,E0,20,23/05/2021,Man City,Everton,5,0,H,2.0,0.0,...,-1.75,2.01,1.89,1.99,1.89,2.20,2.00,2.03,1.85,M Oliver
377,E0,20,23/05/2021,Sheffield United,Burnley,1,0,H,1.0,0.0,...,0.00,2.04,1.86,2.05,1.86,2.17,1.90,2.03,1.84,K Friend
378,E0,20,23/05/2021,West Ham,Southampton,3,0,H,2.0,0.0,...,-0.75,2.00,1.90,2.02,1.91,2.06,2.01,1.99,1.89,M Atkinson
379,E0,20,23/05/2021,Wolves,Man United,1,2,A,1.0,2.0,...,-0.25,2.04,1.86,2.10,1.84,2.10,1.94,2.00,1.88,M Dean